<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h2>Python Demonstration #1:</h2>
</div>

<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h3>Basic Operations</h3>
<b>What is the data type of the column "peak-rpm"? </b>
</div>

In [2]:
  ###
  ### Basic Arithmetic Operations - Part 1-1
  ###

3 * 4

x = 3 * 4

print(x)

# Case Sensitivity

A = 2
print(A)

a = 3
a

# Click on Jupyter Notebook to see the enivronment state after running the code above.  You will see that the value of A is 2 and the value of a is 3.  
# This is because Python is case sensitive.  A and a are two different variables.
#
# When you are peforming an analysis you should monitor the enivromnment state to ensure that the variables and data frames are being properly created and manipulated.  
# This will help you to identify and correct any issues that may arise during the analysis.
#
# If you are using VS Code, you can also use the Data Wrangler Extension to monitor the environment state.  This extension is available in the Visual Studio Code Marketplace.
# The Data Wrangler Extension is a great tool for monitoring the environment state and for debugging your code.  And it is a powerful tool for data analysis, data wrangling, and data visualization.



12
2


3

<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h4>Monitoring the Environment and Processing</h4>
<p>
<p>Install the following extensions to Visual Code Studio<p>
<ol>
    <li>Jupyter Notebook<br>
        a. Click on Jupyter Notebook to see the environment state after running the code above.<br>
        b. You will see that the value of A is 2 and the value of a is 3.<br>
        c. This is because Python is case sensitive.  A and a are two different variables.<br>
    </li>
    <p>   <p>
    <li>Continual Monitoring of the Enviroment<br>
        a. When you are peforming an analysis you should monitor the enivromnment state to ensure that the variables and data frames are being properly created and manipulated. <br>
        b. This will help you to identify and correct any issues that may arise during the analysis.<br>
    <p>   <p>
    <li>Data Wrangler Extension<br>
        a. If you are using VS Code, you can also use the Data Wrangler Extension to monitor the environment state.  This extension is available in the Visual Studio Code Marketplace.<br>
        b. The Data Wrangler Extension is a great tool for monitoring the environment state and for debugging your code.<br>
        c. And it is a powerful tool for data analysis, data wrangling, and data visualization.<br>
    </li>
</ol>
</p>
</div>

In [4]:
  ###
  ### Basic Arithmetic Operations - Part 1-2
  ###

A = 5
a = 2
B = 3
x = 24

print(f"Value of A is {A}")
print(f"Value of a is {a}")
print(f"Is the Value of A = a? {(A == a)}")

# Addition

print("Addition")
print(1+1)
print(1+a)
print(a+A)

print("Subtraction")
print(10-1)
print(10-A)
print(A-a)

print("Multiplication")
print(f"Value of A is {A}")
print(f"Value of a is {a}")
print ("(2*3),(A*2),(7*a),(A*2)")
print((2*3),(A*2),(7*a),(A*2))


Value of A is 5
Value of a is 2
Is the Value of A = a? False
Addition
2
3
7
Subtraction
9
5
3
Multiplication
Value of A is 5
Value of a is 2
(2*3),(A*2),(7*a),(A*2)


KeyboardInterrupt: 

In [5]:
  ###
  ### Basic Vector Operations - Part 1-3
  ###

# BEGIN: Clear all variables and data frames

%reset -f

# END: Clear all variables and data frames

import numpy as np

# ---------------------------- Vector 
# A vector is a sequence of values, all of the same type!
# Vectors are generally created use numpy arrays in Python.

my_numbers = np.array([1, 2, 3, 1, 3, 5, 25])
print(my_numbers)

your_numbers = np.array([5, 31, 71, 1, 3, 21, 6])
print(your_numbers)
print(my_numbers + your_numbers)

x = np.array([2, 4, 6, 8, 10, 6, 7, 8, 9])

print(np.mean(x))
print(np.mean(my_numbers))

y = np.arange(1, 11)  # seq(1, 10) in R
print(y)


[ 1  2  3  1  3  5 25]
[ 5 31 71  1  3 21  6]
[ 6 33 74  2  6 26 31]
6.666666666666667
5.714285714285714


KeyboardInterrupt: 

In [8]:
  ###
  ### Basic Vector Operations - Part 1-4
  ###

# BEGIN: Clear all variables and data frames
%reset -f
# END: Clear all variables and data frames

# ---------------------------- Vector 
# A vector is a sequence of values, all of the same type.
# Vectors are generally created use numpy arrays in Python.

import numpy as np

my_numbers = np.array([1, 2, 3, 1, 3, 5, 25])
print(my_numbers)

your_numbers = np.array([5, 31, 71, 1, 3, 21, 6])
print(your_numbers)
print(my_numbers + your_numbers)

x = np.array([2, 4, 6, 8, 10, 6, 7, 8, 9])

print(np.mean(x))
print(np.mean(my_numbers))

y = np.arange(1, 11)  # seq(1, 10) in R
print(y)


[ 1  2  3  1  3  5 25]
[ 5 31 71  1  3 21  6]
[ 6 33 74  2  6 26 31]
6.666666666666667
5.714285714285714
[ 1  2  3  4  5  6  7  8  9 10]


<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h4>Use of Data Wrangler to Generate Data Transformation Functions</h4>

In [9]:
"""
Cell generated by Data Wrangler.
"""
import pandas as pd

def clean_data(y_df):
    # Change column type to string for column: 0
    y_df = y_df.astype({0: 'string'})
    # Rename column 0 to 'Values_for_Vector_Y'
    y_df = y_df.rename(columns={0: 'Values_for_Vector_Y'})
    return y_df

# Loaded variable 'y' from kernel state
y_df = pd.DataFrame(y.tolist() if len(y.shape) > 2 else y)

y_df_clean = clean_data(y_df.copy())
y_df_clean.head()

Values_for_Vector_Y
0                   1
1                   2
2                   3
3                   4
4                   5

<div style="background-color: #1f77b4; color: #FAFAD2; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h3> Pandas and Numpy Libraries </h3>

The first line, [`import numpy as np`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py"), imports the NumPy library into the current Python script. NumPy, which stands for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. The [`as np`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py") part of the statement is an aliasing convention, allowing you to use [`np`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py") as a shorthand to access NumPy functions, instead of typing [`numpy`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py") each time you need to call a function from the NumPy library.

The second line, [`import pandas as pd`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/__init__.py"), imports the pandas library. Pandas is a powerful and flexible data manipulation tool built on top of the Python programming language. It offers data structures and operations for manipulating numerical tables and time series. Similar to the NumPy import statement, [`as pd`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/__init__.py") serves as an alias, enabling you to use [`pd`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/__init__.py") as a shorthand for pandas. This is particularly useful for accessing pandas functions and methods more succinctly.

Together, these two lines of code set the foundation for performing sophisticated data analysis and manipulation tasks in Python. By importing NumPy and pandas at the beginning of your script, you ensure that all the functionalities provided by these libraries are available for use in your subsequent code.

In [ ]:
  ###
  ### Basic Vector Operations - Part 1-5
  ###

import numpy as np # Importing numpy library to use numpy arrays in Python 
import pandas as pd # Importing pandas library to use pandas dataframes in Python  

# Generate a sequence of numbers from 10 to 100 with a step of 5
x = np.arange(10, 101, 5)
print(x)

# Access element from a vector:
print(x[2])  # Note: Indexing in Python starts from 0

# Display the first 4 elements
print(x[:4])

# Display the first and the third element
print(x[[0, 2]])
print(x[[0, 2, 3]])
print(x)

# Negative index (excluding elements)
print(np.delete(x, 0))  # Exclude the first element
y = np.delete(x, [0, 2])  # Exclude the first and the third element
print(y)

# Length of a vector
print(len(x))

# Sum of all elements in a vector
print(np.sum(x))

# Mean of all elements in a vector
print(np.mean(x))

# Median of all elements in a vector
print(np.median(x))

# Maximum and minimum values in a vector
print(np.max(x))
print(np.min(x))

# Sorting a vector
print(np.sort(x))

# Sorting a vector in descending order
print(-np.sort(-x))

# Handling NA and NaN values
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, np.nan])
mean_x = np.nanmean(x)  # Mean excluding NaN values
print(mean_x)

# Example with NULL values
# Python does not have NULL; it has None. np.nan is used for missing values in arrays.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, None], dtype=object)
print(pd.Series(x).mean(skipna=True))  # Mean excluding None values

# Standard deviation
my_numbers = np.array([1, 2, 3, 1, 3, 5, 25])
print(np.std(my_numbers, ddof=1))  # ddof=1 for sample standard deviation

# Vector operations
print(my_numbers)
print(my_numbers * 5)
print(my_numbers + 1)
print(my_numbers + my_numbers)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
20
[10 15 20 25]
[10 20]
[10 20 25]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[ 15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95 100]
[ 15  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95 100]
19
1045
55.0
55.0
100
10
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10]
4.5
4.5
8.616153157766824
[ 1  2  3  1  3  5 25]
[  5  10  15   5  15  25 125]
[ 2  3  4  2  4  6 26]
[ 2  4  6  2  6 10 50]
