<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h2>Python Demostration #2:</h2>
</div>

<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h3>Data Vectors</h3>
<b>Basic Data Operations</b>
</div>

In [9]:
###
### Example of creating a data frame in Python
###

import pandas as pd

# Create vectors for the data frame
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 35]
salaries = [50000, 55000, 60000]

# Join vectors into a data frame using the DataFrame command
df = pd.DataFrame({'Name': names, 'Age': ages, 'Salary': salaries})

# View the data frame (In Jupyter, you can display the dataframe directly)
print(df)

# Print the data frame
print(df)

# The data frame is a table with rows and columns
print(df['Name']) # Print the Name column
print(df['Age']) # Print the Age column
print(df['Salary']) # Print the Salary column


      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   55000
2  Charlie   35   60000
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   55000
2  Charlie   35   60000
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64
0    50000
1    55000
2    60000
Name: Salary, dtype: int64
Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object
Name        Bob
Age          30
Salary    55000
Name: 1, dtype: object
Name      Charlie
Age            35
Salary      60000
Name: 2, dtype: object
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64
0    50000
1    55000
2    60000
Name: Salary, dtype: int64
Alice
25
50000
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   55000
      Name  Age  Salary
1      Bob   30   55000
2  Charlie   35   60000
    Name  Age
0  Alice   25
1    Bob   30
165000
55000.0
55000.0
5000.0


In [ ]:
###
### Printing the Data Frame by Rows and Columns Using Indexing
###

import pandas as pd

# Printing the Data Frame by Rows and Columns Using Indexing 
print(df.iloc[0, :]) # Print the first row
print(df.iloc[1, :]) # Print the second row
print(df.iloc[2, :]) # Print the third row

print(df.iloc[:, 0]) # Print the first column
print(df.iloc[:, 1]) # Print the second column
print(df.iloc[:, 2]) # Print the third column

print(df.iloc[0, 0]) # Print the first row, first column
print(df.iloc[0, 1]) # Print the first row, second column
print(df.iloc[0, 2]) # Print the first row, third column

print(df.iloc[0:2, :]) # Print the first two rows
print(df.iloc[1:3, :]) # Print the second and third rows
print(df.iloc[0:2, 0:2]) # Print the first two rows and the first two columns

# Summary Operations using a Data frame
print(df['Salary'].sum()) 
print(df['Salary'].mean()) 
print(df['Salary'].median()) 
print(df['Salary'].std())

<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h3>Data Cleaning</h3>
<b>Imputting Missing Values</b>
</div>

In [2]:
###
### Read CSV File into a Data Frame and Clean Outliers - Part 1
###

import pandas as pd
import os

# Read the CSV file into a DataFrame

display(os.getcwd())
datapath = '/Users/rudolphsurovcik/Library/CloudStorage/GoogleDrive-grs3@lehigh.edu/My Drive/Lehigh Fall 2024/Python Developments/Python Fall 2024 Notebooks/Data Files for Python/'

os.chdir(datapath)  # set the working directory to the path where the data files are located 

bank_messy = pd.read_csv("bank_messy.csv")

# View the DataFrame (In Jupyter, you can display the dataframe directly)
print(bank_messy)

# Summary of the DataFrame
print(bank_messy.describe(include='all'))

# Identify outliers in the DataFrame bank_messy

# 1. Find row numbers for NAs in Income, Family, CCAvg, CreditCard, and Loan
print(bank_messy[bank_messy['Income'].isna()])
print(bank_messy[bank_messy['Family'].isna()])
print(bank_messy[bank_messy['CCAvg'].isna()])
print(bank_messy[bank_messy['CreditCard'].isna()])
print(bank_messy[bank_messy['Loan'].isna()])

# Handling Missing Values in the DataFrame bank_messy

# 2. Omit any row that has a variable with an NA value
bank_clean = bank_messy.dropna()

# Summary of the DataFrame bank_clean
print(bank_clean.describe(include='all'))

# 3. Impute the NA value with a value that is representative of the variable

# Impute the NA value with the previous value
bank_clean = bank_messy.fillna(method='ffill')

# Summary of the DataFrame bank_clean
print(bank_clean.describe(include='all'))

'/Users/rudolphsurovcik/Library/CloudStorage/GoogleDrive-grs3@lehigh.edu/My Drive/Lehigh Fall 2024/Python Developments/Python for Course Development'

      Age  Income  Family  CCAvg  Mortgage Online  CreditCard     Education  \
0      25    49.0     4.0    1.6         0     NO         0.0     Undergrad   
1      45    34.0     3.0    1.5         0     NO         0.0     Undergrad   
2      39    11.0     1.0    1.0         0     NO         0.0     Undergrad   
3      35   100.0     1.0    2.7         0     NO         0.0          Grad   
4      35    45.0     4.0    1.0         0     NO         1.0          Grad   
...   ...     ...     ...    ...       ...    ...         ...           ...   
5001   29   328.0     3.0    0.0         0    YES         0.0  Professional   
5002   50     NaN     4.0    NaN         1     NO         NaN     Undergrad   
5003   28   347.0     NaN    NaN         0     NO         1.0          Grad   
5004   27   217.0     1.0    0.3         1     NO         0.0     Undergrad   
5005   22     NaN     NaN    0.5         0     NO         NaN     Undergrad   

      Loan  
0      0.0  
1      0.0  
2      0.0  

/var/folders/rd/bzzc96fj7v9frj3zp_zwgn100000gn/T/ipykernel_15611/2905437772.py:43: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  bank_clean = bank_messy.fillna(method='ffill')


In [5]:
###
### Read CSV File into a Data Frame and Show and Cleaning Outliers - Part 2
###


# Imputation using mean
bank_clean = bank_messy.copy()

bank_clean['Income'] = bank_clean['Income'].fillna(bank_clean['Income'].mean())
bank_clean['Family'] = bank_clean['Family'].fillna(bank_clean['Family'].mean())
bank_clean['CCAvg'] = bank_clean['CCAvg'].fillna(bank_clean['CCAvg'].mean())
bank_clean['CreditCard'] = bank_clean['CreditCard'].fillna(bank_clean['CreditCard'].mean())
bank_clean['Loan'] = bank_clean['Loan'].fillna(bank_clean['Loan'].mean())

# Summary of the DataFrame bank_clean
print(bank_clean.describe(include='all'))

# Imputation using median
bank_clean = bank_messy.copy()

bank_clean['Income'] = bank_clean['Income'].fillna(bank_clean['Income'].median())
bank_clean['Family'] = bank_clean['Family'].fillna(bank_clean['Family'].median())
bank_clean['CCAvg'] = bank_clean['CCAvg'].fillna(bank_clean['CCAvg'].median())
bank_clean['CreditCard'] = bank_clean['CreditCard'].fillna(bank_clean['CreditCard'].median())
bank_clean['Loan'] = bank_clean['Loan'].fillna(bank_clean['Loan'].median())


# Summary of the DataFrame bank_clean Including Objects
print(bank_clean.describe())

# Summary of the DataFrame bank_clean Including Objects
print(bank_clean.describe(include='all'))

                Age       Income       Family        CCAvg     Mortgage  \
count   5006.000000  5006.000000  5006.000000  5006.000000  5006.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean      45.319816    73.952838     2.396283     1.936549    56.431682   
std       11.473437    46.458749     1.147570     1.747312   101.671285   
min       22.000000     8.000000     1.000000     0.000000     0.000000   
25%       35.000000    39.000000     1.000000     0.700000     0.000000   
50%       45.000000    64.000000     2.000000     1.500000     0.000000   
75%       55.000000    98.000000     3.000000     2.500000   101.000000   
max       67.000000   347.000000     4.000000    10.000000   635.000000   

       Online   CreditCard  Education         Loan  
count    5006  5006.000000       5006  5006.00

<div style="background-color: #1f77b4; color: #FFFFE0; padding: 20px; border-radius: 5px; margin-top: 20px; border: 1px solid #b8daff;">
<h3>File Operations</h3>
<b>Import and Exporting data for data frames? </b>
</div>

In [8]:
  ###
  ### Importing a Local File
  ###

#### Load Data and store in dataframe Auto_df

import pandas as pd
import numpy as np
import os


# Define the data path and headers


display(os.getcwd())
datapath = '/Users/rudolphsurovcik/Library/CloudStorage/GoogleDrive-grs3@lehigh.edu/My Drive/Lehigh Fall 2024/Python Developments/Python Fall 2024 Notebooks/Data Files for Python/'

os.chdir(datapath)  # set the working directory to the path where the data files are located 

# Define the data path and headers

headers = [
    "symboling", "normalized-losses", "make", "fuel-type", "aspiration", "num-of-doors", "body-style",
    "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight", "engine-type",
    "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio", "horsepower",
    "peak-rpm", "city-mpg", "highway-mpg", "price"
]

# Load the data into a DataFrame
Auto_df = pd.read_excel('Auto85.xlsx', names=headers)



print(Auto_df)

# Display the first few rows of the dataframe
headrows = Auto_df.head()
print(headrows)

# Describe the data
Auto_85_describe = Auto_df.describe()
print(Auto_85_describe)

# Display the data types of the columns
aut_types = Auto_df.dtypes
print(aut_types)

# save Auto_85_describe to an excel File
Auto_85_describe.to_excel('Auto_85_describe.xlsx')


'/Users/rudolphsurovcik/Library/CloudStorage/GoogleDrive-grs3@lehigh.edu/My Drive/Lehigh Fall 2024/Python Developments/Python Fall 2024 Notebooks/Data Files for Python'

     symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1

<div style="background-color: #006400; color: #FAFAD2; padding: 20px; border-radius: 25px; margin-top: 30px; border: 1px solid #8B0000;">
<h3> Pandas and Numpy Libraries </h3>

The first line, [`import numpy as np`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py"), imports the NumPy library into the current Python script. NumPy, which stands for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. The [`as np`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py") part of the statement is an aliasing convention, allowing you to use [`np`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py") as a shorthand to access NumPy functions, instead of typing [`numpy`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fnumpy%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py") each time you need to call a function from the NumPy library.

The second line, [`import pandas as pd`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/__init__.py"), imports the pandas library. Pandas is a powerful and flexible data manipulation tool built on top of the Python programming language. It offers data structures and operations for manipulating numerical tables and time series. Similar to the NumPy import statement, [`as pd`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/__init__.py") serves as an alias, enabling you to use [`pd`](command:_github.copilot.openSymbolFromReferences?%5B%7B%22%24mid%22%3A1%2C%22fsPath%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22path%22%3A%22%2FLibrary%2FFrameworks%2FPython.framework%2FVersions%2F3.12%2Flib%2Fpython3.12%2Fsite-packages%2Fpandas%2F__init__.py%22%2C%22scheme%22%3A%22file%22%7D%2C%7B%22line%22%3A0%2C%22character%22%3A0%7D%5D "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/__init__.py") as a shorthand for pandas. This is particularly useful for accessing pandas functions and methods more succinctly.

Together, these two lines of code set the foundation for performing sophisticated data analysis and manipulation tasks in Python. By importing NumPy and pandas at the beginning of your script, you ensure that all the functionalities provided by these libraries are available for use in your subsequent code.

In [1]:
  ###
  ### Basic Vector Operations - Part 1-5
  ###

import numpy as np # Importing numpy library to use numpy arrays in Python 
import pandas as pd # Importing pandas library to use pandas dataframes in Python  

# Generate a sequence of numbers from 10 to 100 with a step of 5
x = np.arange(10, 101, 5)
print(x)

# Access element from a vector:
print(x[2])  # Note: Indexing in Python starts from 0

# Display the first 4 elements
print(x[:4])

# Display the first and the third element
print(x[[0, 2]])
print(x[[0, 2, 3]])
print(x)

# Negative index (excluding elements)
print(np.delete(x, 0))  # Exclude the first element
y = np.delete(x, [0, 2])  # Exclude the first and the third element
print(y)

# Length of a vector
print(len(x))

# Sum of all elements in a vector
print(np.sum(x))

# Mean of all elements in a vector
print(np.mean(x))

# Median of all elements in a vector
print(np.median(x))

# Maximum and minimum values in a vector
print(np.max(x))
print(np.min(x))

# Sorting a vector
print(np.sort(x))

# Sorting a vector in descending order
print(-np.sort(-x))

# Handling NA and NaN values
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, np.nan])
mean_x = np.nanmean(x)  # Mean excluding NaN values
print(mean_x)

# Example with NULL values
# Python does not have NULL; it has None. np.nan is used for missing values in arrays.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, None], dtype=object)
print(pd.Series(x).mean(skipna=True))  # Mean excluding None values

# Standard deviation
my_numbers = np.array([1, 2, 3, 1, 3, 5, 25])
print(np.std(my_numbers, ddof=1))  # ddof=1 for sample standard deviation

# Vector operations
print(my_numbers)
print(my_numbers * 5)
print(my_numbers + 1)
print(my_numbers + my_numbers)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
20
[10 15 20 25]
[10 20]
[10 20 25]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[ 15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95 100]
[ 15  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95 100]
19
1045
55.0
55.0
100
10
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10]
4.5
4.5
8.616153157766824
[ 1  2  3  1  3  5 25]
[  5  10  15   5  15  25 125]
[ 2  3  4  2  4  6 26]
[ 2  4  6  2  6 10 50]
